@startuml

title Bet-67 Backend

abstract class User <Entity> <<abstract>> {
    userName : UserName
    firstName : FirstName
    lastName : LastName
    email : Email
    password: Password <<nn, encrypted>>
    phoneNumber: PhoneNumber <<Nullable>>
    creationTS: ZonedDateTime
}

class PhoneNumber <Value Object> <<Embeddable>> {
    reportedCountry: Country
    number: Integer
}

entity Customer <Entity> extends User{
    paymentInformation : PaymentInformation <<nn>>
    credit: Integer
}

entity Bet <Entity> {
    placedOn : Match
    placer : Customer
    type : String
    amount : Integer <<max: 1000 Euro>>
    placedDate: ZonedDateTime
}

' TODO:
' Maybe add functionality for more than 1v1s

entity Match <Entity> {
    sport : Sport
    team1 : Bettable <<nn>>
    team2 : Bettable <<nn>>
    quoteTeam1 : Float
    quoteTeam2 : Float
    date : ZonedDateTime
    winner : String
    arena: Arena <<nn>>
}

entity Arena <Entity> {
    name: String
    type: ArenaType
    location: Location
    possibleSports: List<Sport>
}

class Location <Value Object> <<Embeddable>> {
    longitude: Longitude
    latitude: Latitude
}

abstract class Bettable <Entity> <<abstract>> {
    name: String
    nextMatchDate: ZonedDateTime
}

class WLRatio <Value Object> <<Embeddable>> {
    bettable: Bettable
    ratio: Float <<0.0 - 1.0>>
    sport: Sport
}

entity Team <Entity> extends Bettable{
    sports: List<Sport>
}

entity Athlete <Entity> extends Bettable{
    mainSport: Sport
    additionalSports: List<Sport> <<Nullable>>
    team: Team <<Nullable>>
}

class PaymentInformation <Value Object>  <<Embeddable>> {
    cardNumber : String
    iban : Iban
    reportedCountry : Country
    expirationDate : ZonedDateTime
}

entity Country <Entity> {
    countryName : String
    iso2Code : String
    iso3Code : String
    countryCode : Integer
}

enum Sport <Enum> {
    FOOTBALL,
    BASKETBALL,
    BOXING,
    MMA,
    TENNIS,
    ...
}

Bet "1" --* "0..n" Customer
Customer "1..n" --> "1" PaymentInformation
PaymentInformation "1" -left> "0..n" Country
PhoneNumber "1" --> "0..n" Country
Bet "1" --> "0..n" Match
Match "2" -* "0..n" Bettable
WLRatio "1" --* "0..n" Bettable
Match "1" -* "0..n" Arena
Arena "1" *-- "1" Location
Team "1..n" --> Sport
Athlete "1..n" --> Sport
Match "1" --> Sport
Arena "1..n" -> Sport
User "0..1" --> "1" PhoneNumber
Athlete "0..1" -o "2..n" Team

@enduml